### ISSUE TITLE
How many memory are needed for training?

### ISSUE THREAD

**Issue by CStar-777** [facebookresearch/GuidedDistillation#2]
I use 4 A100, each card's memory is 82.93GiB, and setting batch size=1, but still "out of memory"

**Comment by bratjay01** [comment]
Hey! @CStar-777 did you figure out what the problem was? I'm facing a similar issue while training

**Comment by zaoruis** [comment]
> did you figure out what the problem was? I'm facing a similar issue while training

Hello， did you figure out what the problem was? I'm facing a similar issue while training
