### ISSUE TITLE
Example on COCO with a DINO backbone

### ISSUE THREAD

**Issue by CStar-777** [facebookresearch/GuidedDistillation#3]
Why the “Train semi-supervised model using pretrained checkpoint” in “Example on COCO with a DINO backbone”  use cityscapes's config, which is not same as the stage 1.

**Comment by TariqBerrada** [comment]
Hello, this is just a typo and will be fixed, thanks for the remark.

**Comment by CStar-777** [comment]
> Hello, this is just a typo and will be fixed, thanks for the remark.

Thank you for your reply.

**Comment by kiwi12777** [comment]
Hello, how did you solve this problem?
